name: Unit Test
on: [pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v2
        id: yarn_cache
        with:
          key: modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            modules-${{ hashFiles('**/yarn.lock') }}
            modules-
          path: '**/node_modules'
      - name: install node_modules if cache missed
        if: steps.yarn_cache.outputs.cache-hits != 'true'
        run: yarn install --frozen-lockfile
  
  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - name: restore node_modules
        uses: actions/cache@v2
        id: yarn_cache
        with:
          key: modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            modules-${{ hashFiles('**/yarn.lock') }}
            modules-
          path: '**/node_modules'
      - name: test
        run: yarn test
